version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: space
      MONGO_INITDB_ROOT_PASSWORD: Temporal123
      MONGO_INITDB_DATABASE: catalogue
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local